### ISSUE TITLE
is_visible

### ISSUE THREAD

**Issue by maparent** [Gr1N/SublimeFixMacEnv#1]
Thank you for this plugin, solves a long-standing problem.
Detail: `sublime_plugin.py` complains that `ValueError: ('is_visible must return a bool', ...)`
It would be enough to add this to `SublimeFixMacEnv.py`:
```python
def is_visible():
    return False
```

**Comment by Gr1N** [comment]
Hi,

I currently use VS Code, so I have no chance to create a fix and test it.
But you're always welcome to submit a PR with a fix.

**Comment by maparent** [comment]
done. Sorry for the delay

**Comment by Gr1N** [comment]
Fixed in https://github.com/Gr1N/SublimeFixMacEnv/pull/2
